# Generated by Django 3.1.7 on 2021-03-17 20:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2021)])),
            ],
        ),
        migrations.CreateModel(
            name='CategoriePiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=50)),
                ('prenom_client', models.CharField(max_length=50)),
                ('tel_client', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MarqueVoiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marques', models.CharField(choices=[('RENAULT', 'RENAULT'), ('PEUGEOT', 'PEUGEOT'), ('VOLKS', 'VOLKSWAGEN'), ('OPEL', 'OPEL'), ('CITROEN', 'CITROEN'), ('MB', 'MERCEDEZ_BENZ'), ('BMW', 'BMW'), ('FORD', 'FORD')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PieceVoiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_piece', models.CharField(max_length=200, unique=True)),
                ('prix_piece', models.FloatField()),
                ('desc_piece', models.CharField(max_length=1024)),
                ('categorie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='carPiecesApp.categoriepiece')),
            ],
        ),
        migrations.CreateModel(
            name='ModeleVoiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele_label', models.CharField(choices=[], max_length=25)),
                ('annee', models.ForeignKey(default=2021, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modele', to='carPiecesApp.annee')),
                ('marque', models.ForeignKey(default=2021, on_delete=django.db.models.deletion.RESTRICT, related_name='marque', to='carPiecesApp.marquevoiture')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_piece', models.FloatField()),
                ('qte', models.IntegerField(default=1)),
                ('pieceVoiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligneCommande', to='carPiecesApp.piecevoiture')),
            ],
        ),
        migrations.CreateModel(
            name='CompteClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_client', models.EmailField(max_length=100)),
                ('mdp_client', models.CharField(max_length=50, unique=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compte', to='carPiecesApp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='commande', to='carPiecesApp.client')),
                ('ligneCommande', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='commande', to='carPiecesApp.lignecommande')),
            ],
        ),
        migrations.AddField(
            model_name='categoriepiece',
            name='categorie_modele',
            field=models.ManyToManyField(blank=True, default=None, related_name='categoriePiece', to='carPiecesApp.ModeleVoiture'),
        ),
    ]
